version: '3'

#services:

  # ------------------------------
  # Brokerage containers
  # ------------------------------

  # ------------------------------
  # Private containers
  # ------------------------------